version: "3"

services:
  server:
    build: server/
    ports: 
      - 13000:5000
    depends_on:
      - redis
      - postgres


  client:
    build: client/
    ports: 
      - 13001:80

  redis:
    image: "redis"
    ports:
      - 6379:6379
    volumes:
      - redis-data:/redis/data
    command:
      - '--save 1 1'

  postgres:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  redis-data: